### ISSUE TITLE
Do we need to use sync-request?

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/prana-archaius-client#1]
It's [a dependency](https://github.com/schibsted/prana-archaius-client/blob/master/package.json#L7) to the project. Quote from [their site](https://www.npmjs.com/package/sync-request):

> N.B. You should not be using this in a production application. In a node.js application you will find that you are completely unable to scale your server. In a client application you will find that sync-request causes the app to hang/freeze. Synchronous web requests are the number one cause of browser crashes. For production apps, you should use then-request, which is exactly the same except that it is asynchronous.

**Comment by ghost** [comment]
This has been used when loading config before the server starts. So doing a synchronous request is perfectly fine because you don't want the server to start before it has proper configuration. The synchronous request should not be used when the server is running of course.
